<?cs
####################################################################
# New ticket prelude - Included directly above the new ticket form
?>

<b>Guidelines for tickets:</b>
<ul>
	<li>Please <b>search the existing tickets</b> for your bug, and if one is found, attach additional information to those tickets if applicable, rather than submitting a new ticket.</li>
	<li>Please attach a <b style="color:red">complete, working test case</b> for your bug, that downloads and runs with <b>no additional code required</b> and <b>no external dependencies or modules that dont exist on a normal Python install</b>.  Preferably one that uses an in-memory sqlite engine, if applicable.  (i.e. create_engine('sqlite://') ). 
	><div style="color:red;font-weight:bold;">Please note the SA team does not have the resources to guess what test case might reproduce your behaviorally-observed bug.  Making the effort to produce a working test case is the *only* way to describe and isolate the specific conditions that cause an error, not just a textual description, and creating this test case is *your* job.  Behavioral bug reports that do not include fully working test cases, or at least a significant effort to produce one, will be closed unconditionally.
	</div>

</li>
	<li>Please submit fixes and corrections in <b>Unix patch format</b>, based on the latest SVN tree.  This can be generated by running "svn diff > myfile.txt".  Corrections that are not in patch format are much more tedious to implement, particularly for code I (zzzeek) didnt write (and a lot of the code is contributed at this point).</li>
	<li>Keep an eye on the <b>Timeline</b> for the status of your bug, or subscribe to the <b>sqlalchemy-tickets</b> mailing list.  Bugs can be quickly fixed or marked as invalid and will disappear from the "active" list.</li>
	<li>Please put your <b>email address</b> or <b>some kind of name</b> so I can distinguish who is posting what.</li>
</ul>
